#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANWIDTH=999
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

#PATH modifs
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/code/scripts:$PATH

